name: Run Tests and Lint

on:
  pull_request:
    branches: [ main ]  # Adjust this if your main branch has a different name
  push:
    branches: [ main ]  # Also run on pushes to main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Adjust this to match your project's Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build